title: "Part 1: Year 8 'Relevance' training – Introduction"
hero_image: images/banner1.png
description: Part 1 of the online training course introduces teachers to the intervention and some of the resources for the Year 8 Relevance trial
version: 4
listed: false
copyedit: false
last_tested: "2020-08-19"
steps:
  - title: Introduction to the course
  - title: The Gender Balance in Computing (GBIC) programme
  - title: The Relevance trial
  - title: The Relevance intervention
  - title: Why would girls benefit from considering the relevance of computing to them?
  - title: Data collection using the online survey
  - title: Additional information and guidance
  - title: Summary of Part 1
